language: cpp
matrix:
  include:
    - os: osx
      before_install:
        - brew update
        # Hack around Python 2 -> 3 problems.
        - brew unlink python@2
script:
  - brew tap survex/survex https://git.survex.com/homebrew-survex
  - brew install survex
