name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        runs-on: [macos-latest, macos-10.15]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Update homebrew
        run: |
          brew update
          brew upgrade

      - name: Test installing survex homebrew package
        run: |
          brew tap survex/survex https://git.survex.com/homebrew-survex
          brew install survex
